---
- name: Deploy Maven Artifact (Jenkins User Accessible)
  hosts: localhost


  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: /home/sanjay/deployment
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      ansible.builtin.copy:
        src: /mnt/c/Users/Sanjay/.jenkins/workspace/HelloMaven-CI/target/HelloMaven4-1.0-SNAPSHOT.jar
        dest: /home/sanjay/deployment/HelloMaven.jar
        remote_src: yes